Repository devind-team/eleden, pull requests merged in 2022-05, with the labels that each got.

#150 Переписать components/eleden/ac на composition api
  client/components/eleden/ac/team/AddJob.vue
  client/components/eleden/ac/team/AddJobPost.vue
  client/components/eleden/ac/team/AddStatusHistory.vue
  client/components/eleden/ac/team/AddTeams.vue
  client/components/eleden/ac/team/AddUsers.vue
  client/components/eleden/ac/team/ChangeTeam.vue
  client/components/eleden/ac/team/ChangeTeamEduProgram.vue
  client/components/eleden/ac/team/ChangeTeamResponsibleUsers.vue
  client/components/eleden/ac/team/DeleteTeam.vue
  client/components/eleden/ac/team/GenerateNewPasswords.vue
  client/components/eleden/ac/team/StatusHistory.vue
  client/components/eleden/ac/team/TeamActions.vue
  client/components/eleden/ac/team/UnloadTeams.vue
  client/components/eleden/ac/team/UploadJobs.vue
  client/components/eleden/ac/team/UploadJobsUser.vue
  client/components/eleden/ac/user/ChangeAvatar.vue
  client/components/eleden/ac/user/ConfirmedByUser.vue
  client/components/eleden/ac/user/Jobs.vue
  client/components/eleden/ac/user/Personalities.vue
  client/components/eleden/ac/user/PortfolioFiles.vue
  client/components/eleden/ac/user/Responsible.vue
  client/components/eleden/articles/AddArticleForm.vue
  client/components/eleden/articles/ChangeArticleForm.vue
  client/composables/filters.ts
  client/gql/eleden/fragments/post_fields.graphql
  client/gql/eleden/mutations/team/delete_team.graphql
  client/gql/eleden/queries/education/disciplines.graphql
  client/gql/eleden/queries/team/relative_teams.graphql
  client/gql/eleden/queries/team/teams.graphql
  client/lang/ru/main.ts
  client/pages/eleden/ac/teams/index.vue
  client/pages/index.vue
  client/services/eleden.ts
  client/types/graphql.d.ts
Labels: javascript, refactoring

#152 useResult вынесена в проект отдельно
  client/composables/query-common.ts
  client/composables/query-relay.ts
  client/composables/query-result.ts
Labels: enhancement, javascript

#153 Исправлен API вызова компонента фильтрации
  client/components/common/filters/ItemsDataFilter.vue
  client/components/common/filters/QueryDataFilter.vue
Labels: bug, javascript

#164 Обновлена версия image для клиента
  client/Dockerfile
  client/yarn.lock
  server/poetry.lock
Labels: enhancement, javascript

#165 Исправлены баги при назначении пользователю группу
  client/pages/panel/ac/groups.vue
  client/pages/panel/ac/users.vue
Labels: bug, javascript

#166 Приведено раздела и отображаемых данных
  client/pages/eleden/process/index.vue
Labels: bug, javascript

#168 Исправлена дополнительная подгрузка страниц
  client/components/pages/PageView.vue
  client/gql/pages/queries/pages.graphql
  client/pages/categories/_categoryId.vue
  client/pages/categories/_categoryId/add_page.vue
  client/pages/categories/_categoryId/index.vue
Labels: bug, javascript

#184 Исправлено количество выводимых дисциплин
  client/pages/eleden/edu_programs/_edu_program_id/disciplines.vue
Labels: bug, javascript
