Repository devind-team/eleden, pull requests merged in 2022-04, with the labels that each got.

#39 Исправлена проблема с пагинацией
  client/composables/query-relay.ts
Labels: bug, javascript

#36 Переписаны eleden/edu_programs на composition api
  client/components/eleden/edu_programs/AddCompetences.vue
  client/components/eleden/edu_programs/AddDisciplines.vue
  client/components/eleden/edu_programs/AddEduPrograms.vue
  client/components/eleden/edu_programs/DisciplineForm.vue
  client/components/eleden/edu_programs/DisciplinesTable.vue
  client/components/eleden/edu_programs/EduProgramForm.vue
  client/components/eleden/edu_programs/UnloadEduPrograms.vue
  client/gql/eleden/mutations/edu_programs/delete_edu_hour.graphql
  client/gql/eleden/mutations/edu_programs/delete_methodological_support.graphql
  client/gql/eleden/queries/education/competences.graphql
  client/gql/eleden/queries/education/edu_programs.graphql
  client/pages/eleden/ac/teams/_team_id/edu_program.vue
  client/pages/eleden/edu_programs/_edu_program_id.vue
  client/pages/eleden/edu_programs/_edu_program_id/description.vue
  client/pages/eleden/edu_programs/_edu_program_id/disciplines.vue
  client/pages/eleden/edu_programs/_edu_program_id/settings.vue
  client/pages/eleden/edu_programs/discipline/_discipline_id.vue
  client/pages/eleden/edu_programs/discipline/_discipline_id/competences.vue
  client/pages/eleden/edu_programs/discipline/_discipline_id/description.vue
  client/pages/eleden/edu_programs/discipline/_discipline_id/edu_hours.vue
  client/pages/eleden/edu_programs/discipline/_discipline_id/methodological_support.vue
  client/pages/eleden/edu_programs/discipline/_discipline_id/settings.vue
  client/pages/eleden/edu_programs/index.vue
  server/apps/eleden/schema/mutations/edu_programs_mutations.py
Labels: javascript, refactoring

#43 Добавлены сервисы
  client/components/eleden/edu_programs/AddDisciplines.vue
  client/components/eleden/edu_programs/AddEduPrograms.vue
  client/components/eleden/edu_programs/DisciplinesTable.vue
  client/pages/eleden/edu_programs/_edu_program_id/settings.vue
  client/pages/eleden/edu_programs/discipline/_discipline_id/settings.vue
  client/services/eleden.ts
Labels: javascript

#42 Изменение папки client/.nuxt -> client/nuxt-dist и добавлен yarn.lock
  client/.eslintignore
  client/nuxt.config.ts
  client/tsconfig.json
  client/yarn.lock
Labels: enhancement, javascript

#62 Изменен механизм сборки контейнеров для docker образов клиента и сервера
  .github/dependabot.yml
  client/.dockerignore
  client/Dockerfile
  client/nuxt.config.ts
  client/package.json
  client/schema.graphql
  client/tsconfig.json
  client/types/graphql.d.ts
  client/yarn.lock
  server/Dockerfile
  server/pyproject.toml
Labels: bug, javascript, python

#65 Исправлена проблема с изменением темы
  client/composables/index.ts
  client/composables/vuetify.ts
  client/layouts/default.vue
Labels: bug, javascript

#74 Исправлена проблема с отображением статистики
  client/components/eleden/ac/user/ChangeAvatar.vue
  client/components/eleden/statistics/EduProgramStatisticsChartArc.vue
  client/components/pages/AddCategory.vue
  client/components/pages/EditCategory.vue
Labels: bug, javascript

#76 Проведен рефакторинг некоторых компонентов с целью избавления от RxJS
  .gitignore
  client/components/common/DropFileUpload.vue
  client/components/common/FileField.vue
  client/components/common/ImageGallery.vue
  client/components/common/MutationResultAlert.vue
  client/components/common/filters/QueryDataFilter.vue
  client/components/common/forms/MutationForm.vue
  client/components/dashboard/general/RequestStatistics.vue
  client/components/global/FooterComponent.vue
  client/components/pages/AddCategory.vue
  client/components/pages/AddPage.vue
  client/components/pages/CategoryAction.vue
  client/components/pages/ChangePageKind.vue
  client/components/pages/EditCategory.vue
  client/components/pages/PageContainer.vue
  client/components/pages/PageSections.vue
  client/components/pages/PageSegment.vue
  client/components/pages/PageView.vue
  client/components/pages/SectionActions.vue
  client/components/pages/sections/change/ChangeSectionText.vue
  client/components/pages/sections/views/SectionUsers.vue
  client/components/users/AvatarView.vue
  client/composables/filters.ts
  client/gql/pages/mutations/page/add_page.graphql
  client/gql/pages/queries/pages.graphql
  client/layouts/default.vue
  client/layouts/error.vue
  client/middleware/auth.ts
  client/middleware/check-auth.ts
  client/nuxt.config.ts
  client/package.json
  client/pages/auth/login.vue
  client/pages/auth/logout.vue
  client/pages/auth/recovery/_token.vue
  client/pages/auth/recovery/index.vue
  client/pages/auth/verification.vue
  client/pages/categories/_categoryId.vue
  client/pages/categories/_categoryId/add_page.vue
  client/pages/categories/_categoryId/index.vue
  client/pages/categories/index.vue
  client/pages/messenger.vue
  client/pages/pages/_pageId/section/_sectionId.vue
  client/pages/pages/_pageId/section/add.vue
  client/pages/panel/support/index.vue
  client/pages/profile/index.vue
  client/pages/profile/security.vue
  client/plugins/apollo-init.ts
  client/plugins/apollo.ts
  client/schema.graphql
  client/tsconfig.json
  client/types/graphql.d.ts
  client/types/vue.d.ts
  client/yarn.lock
  server/apps/pages/schema/mutations/page_mutations.py
Labels: dependencies, python

#100 Документирование и очистка
  .gitlab-ci.yml
  docs/code_style/server/models.md
  docs/code_style/server/permissions.md
  init.py
  init.sh
  readme.md
Labels: documentation
