Repository devind-team/eleden, pull requests merged in 2022-03, with the labels that each got.

#20 Обновлена версия nodejs. Скрыты warnings при установке зависимостей
  client/Dockerfile
Labels: enhancement

#15 ref: поправлены небольшие ошибки
  client/components/common/forms/MutationForm.vue
  client/components/global/Subscription.vue
  client/composables/convertors.ts
  client/composables/index.ts
  client/composables/query-relay.ts
  client/gql/eleden/queries/statistics/edu_programs_statistics.graphql
  client/pages/eleden/ac/teams/_team_id.vue
  client/pages/eleden/ac/teams/_team_id/edu_program.vue
  client/pages/eleden/ac/teams/_team_id/settings.vue
  client/pages/eleden/statistics/edu_programs.vue
  client/schema.graphql
  client/types/graphql.d.ts
Labels: javascript, refactoring

#24 Уведомления переписаны на composition api
  client/components/global/Notification.vue
  client/components/notifications/NotificationMenu.vue
  client/components/notifications/NotificationsMenu.vue
  client/components/notifications/NotificationsView.vue
  client/components/notifications/views/NotificationMailingView.vue
  client/components/notifications/views/NotificationPageView.vue
  client/components/pages/PageSections.vue
  client/composables/color-mode.ts
  client/composables/convertors.ts
  client/composables/index.ts
  client/layouts/default.vue
  client/pages/notifications/_notificationId.vue
  client/pages/notifications/_notification_id.vue
  client/pages/notifications/index.vue
  client/services/notifications.ts
Labels: wontfix, javascript

#29 Исправлена проблема получения идентификатора пользователя
  client/layouts/default.vue
Labels: bug, javascript

#33 Добавлены переводы для элементов выгрузки пользователей
  client/lang/ru/ac.ts
Labels: bug, javascript

#35 Убрана функция $snakeToCamel в связи с добавлением scule
  client/components/common/forms/MutationForm.vue
  client/components/common/menu/DateMenu.vue
  client/components/eleden/ac/team/ChangeTeam.vue
  client/components/eleden/statistics/EduProgramFilter.vue
  client/components/notifications/NotificationsView.vue
  client/components/pages/AddPage.vue
  client/components/pages/ChangePageTags.vue
  client/components/pages/ChangePageTitle.vue
  client/components/pages/sections/actions/SectionAction.vue
  client/components/pages/sections/add/AddSectionFiles.vue
  client/components/pages/sections/add/AddSectionGallery.vue
  client/components/pages/sections/add/AddSectionText.vue
  client/components/pages/sections/change/ChangeSectionFiles.vue
  client/components/pages/sections/change/ChangeSectionGallery.vue
  client/components/pages/sections/change/ChangeSectionText.vue
  client/components/sveden/ChangeItemPropContainer.vue
  client/components/sveden/ItemPropContainerAddDialog.vue
  client/composables/convertors.ts
  client/composables/filters.ts
  client/composables/index.ts
  client/package.json
  client/pages/auth/recovery/index.vue
  client/pages/auth/registration.vue
  client/pages/pages/_pageId/index.vue
  client/plugins/utils.ts
  client/types/vue.d.ts
Labels: bug, dependencies, javascript, refactoring
